[package]
name = "actix-food-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.11.0"
diesel = { version = "2.3.1", features = ["sqlite"] }
dotenv = "0.15.0"
serde = "1.0.225"
